idents = [
    "Int8Array",
    "Uint8Array",
    "Uint8ClampedArray",
    "Int16Array",
    "Uint16Array",
    "Int32Array",
    "Uint32Array",
    "Float32Array",
    "Float64Array",
    "Promise",
    "Proxy",
    "async",
    "padStart",
    "padEnd",
    "includes",
    "find",
    "getComputedStyle",
    "FontFace",
    "FontFaceSet",
    "FontFaceSetLoadEvent",
    "MediaSource",
    "sourceBuffers",
    "activeSourceBuffers",
    "readyState",
    "duration",
    "onsourceclose",
    "onsourceended",
    "addSourceBuffer",
    "removeSourceBuffer",
    "endOfStream",
    "setLiveSeekableRange",
    "clearLiveSeekableRange",
    "isTypeSupported",
    "TouchEvent",
    "Touch",
    "TouchList",
    "onpointerover",
    "onpointerenter",
    "onpointerdown",
    "onpointermove",
    "onpointerup",
    "onpointercancel",
    "onpointerout",
    "onpointerleave",
    "ongotpointercapture",
    "onlostpointercapture",
    "setPointerCapture",
    "releasePointerCapture",
    "MutationObserver",
]
keywords = [
    "let",
    "const",
    "class",
    "await",
    "import",
    "export",
    "yield",
]
puncts = [
    "=>",
    "**",
    "...",
    "`",
]
strings = [
    "use strict",
    "sourceopen",
    "touchstart",
    "touchend",
    "touchmove",
    "touchcancel",
    "pointerenter",
    "pointerdown",
    "pointermove",
    "pointerup",
    "pointercancel",
    "pointerout",
    "pointerleave",
    "gotpointercapture",
    "lostpointercapture",
    "pointerover",
]