[book]
authors = ["Robert Masen"]
multilingual = false
src = "src"
title = "Build JavaScript Development Tools with Rust"

[build]
build-dir = "docs"

[output.html]
additional-js = [
    "analytics.js"
]

[preprocessor.presentation-preprocessor]